format = """
$directory
   $character
"""
[directory]
style = "bold blue"
format = "[${path}](bold blue)"
truncation_length = 0 
home_symbol = "~"
[character]
success_symbol = "[▶](bold cyan)"
error_symbol = "[▶](bold red)"
