[window]
opacity = 0.85
blur = true

[colors.bright]
black = "#000000"
blue = "#0000ff"
cyan = "#0d72fc"
green = "#0d72fc"
magenta = "#ff00ff"
red = "#ffff00"
white = "#ffffff"
yellow = "#ffff00"

[colors.normal]
black = "#000000"
blue = "#0000ff"
cyan = "#0d72fc"
green = "#00ff00"
magenta = "#ff00ff"
red = "#0d72fc"
white = "#ffffff"
yellow = "#ffff00"

[font]
size = 9
normal.family = "Ubuntu Mono"
bold.family = "Ubuntu Mono"
italic.family = "Ubuntu Mono"
bold_italic.family = "Ubuntu Mono"


[colors.primary]
background = "#000000"
foreground = "#9999ff"

[cursor]
style = { shape = "Beam", blinking = "On" }

[window.padding]
x = 20
y=20
