[colors]
background = #00182340
background-alt = #141c30
foreground = #f0e6d5
primary = #e49a6b
secondary = #1a2340
alert = #c85940
disabled = #566178

[bar/mybar]
width = 100%
height = 20pt
radius = 0
background = ${colors.background}
foreground = ${colors.foreground}
line-size = 0pt
border-size = 0pt
border-color = #00000000
padding-left = 0
padding-right = 5
module-margin = 3
separator =  
separator-foreground = ${colors.secondary}
font-0 = Ubuntu:style=Bold:pixelsize=12.5
#modules-left = day date time
modules-left = xworkspaces
modules-center = waqt
modules-right = brightness pulseaudio battery wifi-rofi powermenu
enable-ipc = true
font-1 = Font Awesome 6 Free:style=Solid:size=10
font-2 = Font Awesome 6 Brands:style=Regular:size=10
font-3 = Font Awesome 6 Free:style=Regular:size=10
font-4 = JetBrainsMono Nerd Font:size=50


[module/xworkspaces]
type = internal/xworkspaces
label-active = %name%
label-active-background = ${colors.primary}
label-active-foreground = ${colors.secondary}
label-active-padding = 2
label-occupied = %name%
label-occupied-padding = 2
label-urgent = %name%
label-urgent-background = ${colors.alert}
label-urgent-foreground = ${colors.primary}
label-urgent-padding = 2
label-empty = %name%
label-empty-foreground = ${colors.disabled}
label-empty-padding = 2
tail = true
enable-click = false
enable-scroll = false

[module/pulseaudio]
type = internal/pulseaudio
format-volume-prefix = "  "
format-volume-prefix-foreground = ${colors.primary}
format-volume = <label-volume>
label-volume = %percentage%%
label-muted = 
label-muted-foreground = ${colors.disabled}

[module/waqt]
type = internal/date
interval = 1
date =  %H:%M
date-alt = %d, %B %Y   %A
#date-alt = %a %d %b, %R
format-prefix = "   "
format-prefix-foreground = ${colors.primary}
format = <label>
label = %date%
label-foreground = ${colors.foreground}

[module/date]
type = internal/date
interval = 1
date = %d, %b
date-alt = 
label = %date%
label-foreground = ${colors.primary}

[module/day]
type = internal/date
interval = 1
date = %a
date-alt =
label = %date%
label-foreground = ${colors.primary}

[module/time]
type = internal/date
interval = 1
date = %H:%M
date-alt = %H:%M
label = %date%
label-foreground = ${colors.primary}

[module/brightness]
type = custom/script
exec = brightnessctl | awk -F'[()]' '/Current brightness/ {print $2}'
interval = 1
format-prefix = " "
format-prefix-foreground = ${colors.primary}
format = <label>
label = %output%


[module/battery]
type = internal/battery
battery = BAT0
adapter = ACAD
full-at = 99

format-discharging-prefix = "  "
format-charging-prefix = " "
format-full-prefix = "  "

format-discharging-prefix-foreground = ${colors.primary}
format-charging-prefix-foreground = ${colors.primary}
format-full-prefix-foreground = ${colors.primary}

format-discharging = <label-discharging>
format-charging = <label-charging>
format-full = <label-full>

label-discharging = %percentage%%
label-charging = %percentage%%
label-full = %percentage%%

interval = 1

[module/wifi-rofi]
type = custom/script
exec = ~/.config/polybar/scripts/wifi-rofi.sh --status
click-left = ~/.config/polybar/scripts/wifi-rofi.sh
interval = 10
label = %output%
label-foreground = ${colors.primary}
label-font = 1

[module/powermenu]
type = custom/text
label = 
label-foreground = ${colors.primary}
click-left = ~/.config/polybar/scripts/powermenu.sh

[settings]
screenchange-reload = true
pseudo-transparency = false

